services:
  python-image-modification:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-image-modification
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    networks:
      - python-image-modification-net

  python-backround-modification-validation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-backround-modification-validation
    environment:
      PYTHONUNBUFFERED: 1
    command: ["python", "-m", "app.services.background_validator"]
    restart: unless-stopped
    networks:
      - python-image-modification-net

networks:
  python-image-modification-net:
    driver: bridge
